# Generated by Django 5.1.7 on 2025-04-08 07:21

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=20)),
                ('prijmeni', models.CharField(max_length=20)),
                ('vek', models.IntegerField(validators=[users.models.vek])),
                ('adresa', models.CharField(max_length=50)),
                ('pohlavi', models.CharField(choices=[('M', 'Muž'), ('Z', 'Žena'), ('N', 'Nechci zmiňovat')], max_length=1)),
                ('telefon', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.IntegerField()),
                ('typ_uctu', models.CharField(choices=[('B', 'Běžný účet'), ('S', 'Spořící účet'), ('U', 'Úvěrový účet')], max_length=1)),
                ('mena', models.CharField(choices=[('CZK', 'ČESKÁ KORUNA'), ('EUR', 'EURO'), ('USD', 'DOLLAR')], max_length=3)),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='users.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_transakce', models.CharField(choices=[('V', 'Vklad'), ('VY', 'Výběr'), ('P', 'Platba')], max_length=2)),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.customers')),
            ],
        ),
    ]
